export const SET_QUERY = 'SET_QUERY';
export const FETCH_ROBOTS = 'FETCH_ROBOTS';
export const DATA_FETCH_DID_ERR = 'DATA_FETCH_DID_ERR';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const POPULATE_ROBOTS = 'POPULATE_ROBOTS';
export const DATA_IS_FETCHING = 'DATA_IS_FETCHING';